# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
aqualogic:
  host: 192.168.42.117
  port: 80

sensor:
  - platform: aqualogic
    monitored_conditions:
      - pool_temp

switch:
  - platform: aqualogic
    monitored_conditions:
      - lights
      - filter
