---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: ${reboot_timeout}
  fast_connect: off
  ap:
    ssid: ${device}
    password: !secret ap_wifi_password
captive_portal: