---
strobe:
  name: Danger Will Robinson
  colors:
    - state: True
      brightness: 100%
      red: 100%
      green: 0%
      blue: 0%
      duration: 300ms
    - state: False
      duration: 300ms