---
strobe:
  name: Ring Doorbell
  colors:
    - state: True
      brightness: ${sub_led_max_brightness_level1}
      red: 100%
      green: 100%
      blue: 100%
      duration: 700ms
    - state: False
      duration: 700ms