---
strobe:
  name: Wifi Connecting
  colors:
    - state: True
      brightness: ${sub_led_max_brightness_level1}
      red: 30%
      green: 30%
      blue: 0%
      duration: 500ms
    - state: False
      duration: 500ms