esphome:
  name: 8266-template-device
  friendly_name: 8266 Template Device

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "tLS2euWdvTGDw7j3mnWhTiTEP2l/OWxO3gUudrnMDOY="

ota:
  - platform: esphome
    password: "5bb6f7bdbab8fcb6d62e9247afafb99a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "8266-Template-Device"
    password: "URVh5BFh5nfR"

captive_portal:

# Example configuration entry
light:
  - platform: status_led
    name: "Switch state"
    pin:
      number: GPIO2
      inverted: true