substitutions:
  device: batt_volt_test
  name: Battery Voltage Test
  location: Test
  reboot_timeout: 1h
  update_interval: 10s
  update_interval_memory_usage: 5s
  update_interval_wifi_status: 10s
  update_interval_short: 10s
  sliding_window: "1"
  logger_baud_rate: "115200"
  adc_a0_pin: A0
  adc_a0_multiplier: "4.2"
  adc_a0_pin_name: "Battery (18650)"
  adc_a0_icon: "mdi:battery"
  adc_a0_accuracy_decimals: '2'
  adc_a0_unit_of_measurement: "V"
  # Deep Sleep config
  run_duration: 60s
  sleep_duration: 10min

esphome:
  name:  ${device}
  platform: ESP8266
  board: d1_mini

<<: !include common/deep_sleep.yaml

<<: !include common/wifi.yaml
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/text_sensors.yaml
<<: !include common/logger.yaml
<<: !include common/binary_sensors.yaml

#################################################################
# Sensor Configuration
#################################################################
sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml
  - !include common/analog_sensor/adc_a0.yaml

#################################################################
# Misc setup
#################################################################
switch:
   - !include common/switch/restart.yaml
   
