---
  substitutions:
    device: ir_code_capture
    reboot_timeout: 1d
    name: IR Code Capture
    location: Test
    update_interval: 10min
    update_interval_memory_usage: 5s
    update_interval_wifi_status: 1min
    update_interval_short: 10s
    logger_baud_rate: "115200"
    ir_receiver_pin: GPIO5
    ir_transmitter_pin: GPIO4
    ir_device_name: Window Vent

  esphome:
    name: ${device}
    platform: ESP8266
    board: d1_mini
  
  <<: !include common/wifi.yaml
  <<: !include common/api.yaml
  <<: !include common/ota.yaml
  <<: !include common/text_sensors.yaml
  <<: !include common/logger.yaml

  select:
    - platform: template
      name: "Template select"
      optimistic: true
      options:
        - one
        - two
        - three
      initial_option: two
        
  sensor:
    - !include common/sensor/wifi-signal.yaml
    - !include common/sensor/uptime.yaml
    
  text_sensor:
    - platform: homeassistant
      name: "AccuWeather"
      entity_id: sensor.home_realfeel_temperature
      internal: true
      on_value:
        then:
          - lambda: |-
              ESP_LOGD("main", "The current value of x is %s", x.c_str());
              float result = std::atof(x.c_str());
              ESP_LOGD("main", "The current value is result %f", result);
              if ( result < 74.0  )
              {
                id(power).turn_on();
              } else {
                id(power).turn_off();
              }
    - platform: homeassistant
      name: "OpenWeatherMAp"
      entity_id: sensor.openweathermap_temperature
      internal: true

  <<: !include common/ir_remote_receiver.yaml
  <<: !include common/ir_remote_transmitter.yaml

  switch:
    - platform: template
      name: ${ir_device_name} Power
      id: power
      turn_on_action:
        - switch.template.publish:
            id: power
            state: ON
        - remote_transmitter.transmit_raw:
            carrier_frequency: 38kHz
            <<: !include common/ir_codes/window_vent/power.yaml
      turn_off_action:
          then:
            - switch.template.publish:
                id: power
                state: OFF
            - remote_transmitter.transmit_raw:
                carrier_frequency: 38kHz
                <<: !include common/ir_codes/window_vent/power.yaml
            - delay: 1s
            - remote_transmitter.transmit_raw:
                carrier_frequency: 38kHz
                <<: !include common/ir_codes/window_vent/power.yaml
    - platform: template
      name: ${ir_device_name} Direction Toggle
      turn_on_action:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 38kHz
            <<: !include common/ir_codes/window_vent/direction.yaml
    - platform: template
      name: ${ir_device_name} Increase Speed
      turn_on_action:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 38kHz
            <<: !include common/ir_codes/window_vent/speed_up.yaml
    - platform: template
      name: ${ir_device_name} Decrease Speed
      turn_on_action:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 38kHz
            <<: !include common/ir_codes/window_vent/speed_down.yaml
      